apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: odoo-configmap
          env:
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_DATABASE
              value: odoo
            - name: POSTGRES_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-secret
                  key: POSTGRES_USER_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-secret
                  key: POSTGRES_PASSWORD
