apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-payment
  template:
    metadata:
      labels:
        app: busybox-payment
    spec:
      containers:
      - name: busybox-payment
        image: busybox:1.36.0
        command:
        - sh
        - -c
        - |
          echo "MERCHANT_ID: $MERCHANT_ID"
          echo "PAYMENT_GATEWAY_API_KEY: $PAYMENT_GATEWAY_API_KEY"
        envFrom:
        - configMapRef:
            name: payment-config
        env:
        - name: PAYMENT_GATEWAY_API_KEY
          valueFrom:
            secretKeyRef:
              name: payment-gateway-api-key
              key: PAYMENT_GATEWAY_API_KEY
