apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo
  namespace: odoo
spec:
  storageClassName: "my-gce-pd" ## IMPORTANT - this enables auto PV creating
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
