apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  namespace: odoo
type: Opaque
data:
  ODOO_DATABASE_PASSWORD: Yml0bmFtaQ==
  POSTGRES_USER_PASSWORD: Yml0bmFtaQ==
  POSTGRES_PASSWORD: Yml0bmFtaQ==
  ODOO_USER_PASSWORD: Yml0bmFtaQ==
