apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zadanie-pvc
  namespace: zadanie
spec:
  storageClassName: "my-gce-pd" ## IMPORTANT - this enables auto PV creating
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
